### ISSUE TITLE
sigh repair: `map': undefined method `id' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by krzyzanowskim** [fastlane/sigh#197]
```
$ sigh repair
[03:59:34]: Successfully logged in
[03:59:40]: Going to repair 5 provisioning profiles
[03:59:40]: Repairing profile 'XC: com.hakore.pgpmessenger.PGPMessengerExtension'...
/Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/spaceship-0.13.0/lib/spaceship/portal/provisioning_profile.rb:336:in `map': undefined method `id' for nil:NilClass (NoMethodError)
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/spaceship-0.13.0/lib/spaceship/portal/provisioning_profile.rb:336:in `block in update!'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/spaceship-0.13.0/lib/spaceship/client.rb:178:in `call'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/spaceship-0.13.0/lib/spaceship/client.rb:178:in `with_retry'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/spaceship-0.13.0/lib/spaceship/portal/provisioning_profile.rb:330:in `update!'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/spaceship-0.13.0/lib/spaceship/portal/provisioning_profile.rb:311:in `repair!'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/sigh-1.1.1/lib/sigh/repair.rb:24:in `block in repair_all'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/sigh-1.1.1/lib/sigh/repair.rb:22:in `each'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/sigh-1.1.1/lib/sigh/repair.rb:22:in `repair_all'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/sigh-1.1.1/bin/sigh:55:in `block (2 levels) in run'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/sigh-1.1.1/bin/sigh:89:in `run'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/gems/sigh-1.1.1/bin/sigh:107:in `<top (required)>'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/bin/sigh:23:in `load'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/bin/sigh:23:in `<main>'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
	from /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by shodanuk** [comment]
I've also experienced this today whilst attempting to repair provisioning profiles using sigh.

I've running sigh v1.3.0 and ruby v2.0.0p645

**Comment by KrauseFx** [comment]
@krzyzanowskim Please update to the latest release of `sigh` and `spaceship`

**Comment by shodanuk** [comment]
@KrauseFx I already have Sigh 1.3.0 & Spaceship 0.19.3 but am still experiencing this issue.

I'll add my stack trace although I think it's almost identical to OP's

````
/Users/terrymorgan/.gem/ruby/2.0.0/gems/spaceship-0.19.3/lib/spaceship/portal/provisioning_profile.rb:350:in `map': undefined method `id' for nil:NilClass (NoMethodError)
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/spaceship-0.19.3/lib/spaceship/portal/provisioning_profile.rb:350:in `block in update!'
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/spaceship-0.19.3/lib/spaceship/client.rb:186:in `call'
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/spaceship-0.19.3/lib/spaceship/client.rb:186:in `with_retry'
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/spaceship-0.19.3/lib/spaceship/portal/provisioning_profile.rb:344:in `update!'
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/spaceship-0.19.3/lib/spaceship/portal/provisioning_profile.rb:317:in `repair!'
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/sigh-1.3.0/lib/sigh/repair.rb:24:in `block in repair_all'
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/sigh-1.3.0/lib/sigh/repair.rb:22:in `each'
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/sigh-1.3.0/lib/sigh/repair.rb:22:in `repair_all'
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/sigh-1.3.0/bin/sigh:56:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/sigh-1.3.0/bin/sigh:90:in `run'
	from /Users/terrymorgan/.gem/ruby/2.0.0/gems/sigh-1.3.0/bin/sigh:108:in `<top (required)>'
	from /Users/terrymorgan/bin/sigh:23:in `load'
	from /Users/terrymorgan/bin/sigh:23:in `<main>'
````

**Comment by YissacharB** [comment]
@KrauseFx I have Sigh 1.3.1 & Spaceship 0.19.4 and i also experiencing this issue.


```
$ sigh repair --username ****@****.com
[12:05:56]: Starting login with user '****@****.com'
[12:05:58]: Successfully logged in
[12:06:00]: Going to repair 43 provisioning profiles
[12:06:00]: Repairing profile '***** Development'...

Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '951cdfc2bc2e2e8e90d539ff3b5f1bbc'
The crash report has been stored locally '/tmp/sentry_951cdfc2bc2e2e8e90d539ff3b5f1bbc.json'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/portal/provisioning_profile.rb:350:in `map': [!] undefined method `id' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/portal/provisioning_profile.rb:350:in `block in update!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/client.rb:186:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/client.rb:186:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/portal/provisioning_profile.rb:344:in `update!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.4/lib/spaceship/portal/provisioning_profile.rb:317:in `repair!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.3.1/lib/sigh/repair.rb:24:in `block in repair_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.3.1/lib/sigh/repair.rb:22:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.3.1/lib/sigh/repair.rb:22:in `repair_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.3.1/bin/sigh:56:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.4/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.3.1/bin/sigh:90:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.3.1/bin/sigh:108:in `<top (required)>'
	from /usr/local/bin/sigh:23:in `load'
	from /usr/local/bin/sigh:23:in `<main>'
```

do you need also the crash log?

**Comment by KrauseFx** [comment]
Do you have registered devices on this account?

**Comment by KrauseFx** [comment]
Can you share a screenshot of your Devices tab?

**Comment by YissacharB** [comment]
@KrauseFx  yes i have

**Comment by YissacharB** [comment]
![devices](https://cloud.githubusercontent.com/assets/7419531/13054526/f559295a-d412-11e5-8fab-bf3f36c4b56a.PNG)

**Comment by KrauseFx** [comment]
The upload didn't work

**Comment by YissacharB** [comment]
![devices](https://cloud.githubusercontent.com/assets/7419531/13054872/a6762de0-d414-11e5-96e0-a7c86282b336.PNG)
this is what you need?

**Comment by YissacharB** [comment]
@KrauseFx do you have any work around?

**Comment by KrauseFx** [comment]
Does this happen to every provisioning profile or only on some of them? Anything special on some of those profiles? Do you have tvOS?

**Comment by KrauseFx** [comment]
Any updates on this?
