### ISSUE TITLE
Sigh crashes after entering iTunes password

### ISSUE THREAD

**Issue by sasikiran** [fastlane/sigh#213]
I am giving this - 

$ sigh --adhoc -a com.appname.appname -u redacted@redacted.com

I got to enter the password once. I am not sure whether I entered the right password. How do I remove the stored password? 

Also, the app crashes immediately after entering the password with the following output - 

``` ruby
Starting login with user 'redacted@redacted.com'
/Users/sasikiran/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from /Users/sasikiran/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/sasikiran/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /Users/sasikiran/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/sasikiran/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/sasikiran/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/sasikiran/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/sasikiran/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1133:in `get'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/spaceship-0.14.1/lib/spaceship/portal/portal_client.rb:22:in `api_key'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/spaceship-0.14.1/lib/spaceship/portal/portal_client.rb:37:in `send_login_request'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/spaceship-0.14.1/lib/spaceship/client.rb:160:in `login'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/spaceship-0.14.1/lib/spaceship/client.rb:54:in `login'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/spaceship-0.14.1/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/spaceship-0.14.1/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/sigh-1.1.3/lib/sigh/runner.rb:15:in `run'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/sigh-1.1.3/lib/sigh/manager.rb:7:in `start'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/sigh-1.1.3/bin/sigh:34:in `block (2 levels) in run'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/sigh-1.1.3/bin/sigh:89:in `run'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/gems/sigh-1.1.3/bin/sigh:107:in `<top (required)>'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/bin/sigh:23:in `load'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/bin/sigh:23:in `<main>'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sasikiran/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

Edit: I am using sigh 1.1.3

**Comment by KrauseFx** [comment]
Can you try following the SSL guide? https://github.com/fastlane/fastlane/blob/master/docs/FAQs.md#im-getting-an-ssl-error

**Comment by sasikiran** [comment]
Hi @KrauseFx , thanks for the response. I checked the guide. Brew reported that I am already using the latest version of openssl. 

It looks like the issue is caused because of rvm. I was using ruby 2.2.3. I revert back to system ruby and retried it. The crash no longer happened.

**Comment by humblehacker** [comment]
I'm running into the same issue on OS X 10.11.2 with the system ruby (2.2.1).  I installed rvm and switch to ruby 2.1.5, but the error persists.  Any ideas?

**Comment by postmechanical** [comment]
Running into the exact same error:

    Error: openssl 1.0.2e already installed
    The command "brew update && brew upgrade openssl" failed and exited with 1 during .

**Comment by jeeftor** [comment]
I just hit the exact same error today

**Comment by wattson12** [comment]
I'm seeing the same error here as well. Sigh version is 1.2.2, ruby version is 2.2.1, and updating openssl via homebrew tells me "openssl 1.0.2e_1 already installed"

Is there anything else to check?
