### ISSUE TITLE
Crash creating dev profile when no devices

### ISSUE THREAD

**Issue by carlosefonseca** [fastlane/sigh#214]
Hi!

Just tried to create a development profile profile but the account doesn't have devices and so `sigh` crashed.

The messages in the crash are pretty straight forward, but maybe you could handle this case a but more gracefully. :)

```
/Users/carlos/.gems/gems/spaceship-0.14.1/lib/spaceship/client.rb:263:in `parse_response': 
{"responseId"=>"8cdf8d72-97c2-4893-be6f-9ae5f81ca178", "resultCode"=>35,
"resultString"=>"There were errors in the data supplied. Please correct and re-submit.", 
"userString"=>"There are no current devices on this team matching the provided device IDs.", 
"creationTimestamp"=>"2015-11-18T22:29:17Z", "protocolVersion"=>"QH65B2", "requestId"=>nil, 
"userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action", 
"httpCode"=>200, "validationMessages"=>[{"validationKey"=>"deviceIds", 
"validationUserMessage"=>"There are no current devices on this team matching the provided device IDs."}]} (Spaceship::Client::UnexpectedResponse)
	from /Users/carlos/.gems/gems/spaceship-0.14.1/lib/spaceship/portal/portal_client.rb:332:in `create_provisioning_profile!'
	from /Users/carlos/.gems/gems/spaceship-0.14.1/lib/spaceship/portal/provisioning_profile.rb:222:in `block in create!'
	from /Users/carlos/.gems/gems/spaceship-0.14.1/lib/spaceship/client.rb:178:in `call'
	from /Users/carlos/.gems/gems/spaceship-0.14.1/lib/spaceship/client.rb:178:in `with_retry'
	from /Users/carlos/.gems/gems/spaceship-0.14.1/lib/spaceship/portal/provisioning_profile.rb:221:in `create!'
	from /Users/carlos/.gems/gems/sigh-1.1.3/lib/sigh/runner.rb:104:in `create_profile!'
	from /Users/carlos/.gems/gems/sigh-1.1.3/lib/sigh/runner.rb:38:in `run'
	from /Users/carlos/.gems/gems/sigh-1.1.3/lib/sigh/manager.rb:7:in `start'
	from /Users/carlos/.gems/gems/sigh-1.1.3/bin/sigh:34:in `block (2 levels) in run'
	from /Users/carlos/.gems/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/carlos/.gems/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/carlos/.gems/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/carlos/.gems/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/carlos/.gems/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/carlos/.gems/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/carlos/.gems/gems/sigh-1.1.3/bin/sigh:89:in `run'
	from /Users/carlos/.gems/gems/sigh-1.1.3/bin/sigh:107:in `<top (required)>'
	from /Users/carlos/.gems/bin/sigh:23:in `load'
	from /Users/carlos/.gems/bin/sigh:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Thanks for the feedback, @snatchev will take a look on how we can improve this :rocket:

**Comment by jaroslavas** [comment]
Here is a log for the newest sigh version :)

```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/client.rb:268:in `parse_response': {"responseId"=>"3958a499-850e-4f31-ac81-8501b23c9eb7", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"There are no current devices on this team matching the provided device IDs.", "creationTimestamp"=>"2016-01-20T12:41:02Z", "protocolVersion"=>"QH65B2", "requestId"=>nil, "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/profile/createProvisioningProfile.action", "httpCode"=>200, "validationMessages"=>[{"validationKey"=>"deviceIds", "validationUserMessage"=>"There are no current devices on this team matching the provided device IDs."}]} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/portal/portal_client.rb:363:in `create_provisioning_profile!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/portal/provisioning_profile.rb:227:in `block in create!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/client.rb:186:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/client.rb:186:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.19.1/lib/spaceship/portal/provisioning_profile.rb:226:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.2/lib/sigh/runner.rb:109:in `create_profile!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.2/lib/sigh/runner.rb:39:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.2/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.2/bin/sigh:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.2/bin/sigh:90:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.2.2/bin/sigh:108:in `<top (required)>'
	from /usr/bin/sigh:23:in `load'
	from /usr/bin/sigh:23:in `<main>'
```
