### ISSUE TITLE
Couldn't download certificate

### ISSUE THREAD

**Issue by gran33** [fastlane/sigh#257]
While using ```sigh``` getting this error:
```
/Users/rang/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.19.3/lib/spaceship/portal/portal_client.rb:318:in `download_certificate': Couldn't download certificate, got this instead:  (Spaceship::Client::UnexpectedResponse)
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.19.3/lib/spaceship/portal/certificate.rb:298:in `download_raw'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/lib/sigh/runner.rb:87:in `block (2 levels) in fetch_profiles'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/lib/sigh/runner.rb:85:in `each'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/lib/sigh/runner.rb:85:in `block in fetch_profiles'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/lib/sigh/runner.rb:82:in `each'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/lib/sigh/runner.rb:82:in `find_all'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/lib/sigh/runner.rb:82:in `fetch_profiles'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/lib/sigh/runner.rb:20:in `run'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/lib/sigh/manager.rb:7:in `start'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/bin/sigh:35:in `block (2 levels) in run'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/bin/sigh:90:in `run'
	from /Users/rang/.rvm/gems/ruby-2.2.1@global/gems/sigh-1.3.0/bin/sigh:108:in `<top (required)>'
	from /Users/rang/.rvm/rubies/ruby-2.2.1/bin/sigh:23:in `load'
	from /Users/rang/.rvm/rubies/ruby-2.2.1/bin/sigh:23:in `<main>'
	from /Users/rang/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rang/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by gustavogervasio** [comment]
I have the same problem:

 [!] Couldn't download certificate, got this instead: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> (Spaceship::Client::UnexpectedResponse)

**Comment by KrauseFx** [comment]
Sorry for not coming back earlier. Do you still experience this issue with the latest version of `spaceship`?

**Comment by cuongta** [comment]
I have a similar problem when I try to run sigh:

/Library/Ruby/Gems/2.0.0/gems/spaceship-0.21.1/lib/spaceship/portal/portal_client.rb:311:in `download_certificate': [!] Couldn't download certificate, got this instead: HTTP 405 Method Not Allowed (Spaceship::Client::UnexpectedResponse)

Thanks

**Comment by KrauseFx** [comment]
Sorry about this, we already pushed a new version of spaceship: https://github.com/fastlane/spaceship/releases/tag/0.22.0. Please update using `sudo gem update spaceship` and let us know if that solves the issue :rocket:

**Comment by mfurtak** [comment]
[`sigh` 1.4.0](https://github.com/fastlane/sigh/releases/tag/1.4.0) has been released with this fix as well! :tada:

**Comment by cuongta** [comment]
sweet, thanks for the quick response! it works now.

**Comment by asfalcone** [comment]
@gran33 are you still experiencing the original problem?
