### ISSUE TITLE
Wildcard for Enterprise

### ISSUE THREAD

**Issue by uny** [fastlane/sigh#260]
I would like to use sigh for wildcard provisioning profile of enterprise account.

|Summary for sigh 1.3.1||
|:---:|:---:|
|adhoc|false|
|skip_install|false|
|development|false|
|app_identifier|*|
|ignore_profiles_with_different_name|false|
|skip_fetch_profiles|false|
|skip_certificate_verification|false|

Then, I am getting the error:
```
.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spaceship-0.20.0/lib/spaceship/portal/portal_client.rb:311:in `download_certificate': [!] Couldn't download certificate, got this instead: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> (Spaceship::Client::UnexpectedResponse)


<html lang="en-us">
<head>
	<title>Try your request again.</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="pics-label" content='(pics-1.1 "http://www.icra.org/ratingsv02.html" l gen true for "http://www.apple.com" r (cz 1 lz 1 nz 1 oz 1 vz 1) "http://www.rsac.org/ratingsv01.html" l gen true for "http://www.apple.com" r (n 0 s 0 v 0 l 0))'>
	<meta name="Author" content="Apple Inc.">
	<meta name="viewport" content="width=1024">
	<link rel="stylesheet" type="text/css" href="https://devimages.apple.com.edgekey.net/global/styles/ext/2.2/ext-all.css" />
	<link rel="stylesheet" type="text/css" href="https://devimages.apple.com.edgekey.net/assets/apps/styles/asst/1.0/xtheme-developer.css" />
	<link rel="stylesheet" href="https://devimages.apple.com.edgekey.net/assets/styles/base.css" type="text/css" charset="utf-8">
	<link rel="stylesheet" href="https://devimages.apple.com.edgekey.net/assets/styles/adc.css" type="text/css" charset="utf-8">
	<script src="https://devimages.apple.com.edgekey.net/global/scripts/lib/prototype.js" type="text/javascript" charset="utf-8"></script>
	<script src="https://devimages.apple.com.edgekey.net/global/scripts/lib/scriptaculous.js" type="text/javascript" charset="utf-8"></script>
	<script src="https://devimages.apple.com.edgekey.net/global/scripts/browserdetect.js" type="text/javascript" charset="utf-8"></script>
	<script src="https://devimages.apple.com.edgekey.net/global/scripts/apple_core.js" type="text/javascript" charset="utf-8"></script>
	<script src="https://devimages.apple.com.edgekey.net/global/scripts/search_decorator.js" type="text/javascript" charset="utf-8"></script>
	<script src="https://devimages.apple.com.edgekey.net/global/scripts/adc_core.js" type="text/javascript" charset="utf-8"></script>
	<script type="text/javascript" charset="utf-8">
		document.write('<link rel="stylesheet" type="text/css" href="https://devimages.apple.com.edgekey.net/assets/styles/script.css" media="screen">')
	</script>
</head>
<body id="error">
	<div id="globalheader">
	<h1><a href="/">Apple Developer</a></h1>
	<ul id="gh-nav">
		<li id="gh-nav-technologies"><a href="/technologies/">Technologies</a></li>
		<li id="gh-nav-resources"><a href="/resources/">Resources</a></li>
		<li id="gh-nav-devcenters"><a href="/programs/">Programs</a></li>
		<li id="gh-nav-support"><a href="/support/">Support</a></li>
		<li id="gh-nav-membercenter"><a href="/membercenter/">Member Center</a></li>
	</ul>

	
</div>
			


	<div id="content" class="box">
		<div class="cap boxtop"></div>	
			<div class="msg warn">
				<h4>We are unable to process your request.</h4>
				<p>An unknown error occurred. Please <a href="index.action">try again</a>.
			</div><!--/msg-->
		<div class="cap boxbottom"></div>
	</div>
	
<div id="globalfooter">
	<p class="gf-buy">Shop the <a href="http://www.apple.com/store/">Apple Online Store</a> (1-800-MY-APPLE), visit an <a href="http://www.apple.com/retail/">Apple Retail Store</a>, or find a <a href="http://www.apple.com/buy/locator/">reseller</a>.</p>	
	<ul class="gf-links piped">
		<li><a class="first" href="/sitemap/">Site Map</a></li>
		<li><a href="/rss/">RSS Feeds</a></li>

	</ul>	
	<div class="gf-sosumi">
		<p>Copyright &copy; <script>document.write(new Date().getFullYear())</script> Apple Inc. All rights reserved.</p>
		<ul class="piped">
			<li><a href="http://www.apple.com/legal/terms/site.html" class="first">Terms of Use</a></li>
			<li><a href="http://www.apple.com/legal/privacy/">Privacy Policy</a></li>
		</ul>

	</div>
</div><!--/globalfooter-->
</body>
</html>

	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/spaceship-0.20.0/lib/spaceship/portal/certificate.rb:298:in `download_raw'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/lib/sigh/runner.rb:87:in `block (2 levels) in fetch_profiles'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/lib/sigh/runner.rb:85:in `each'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/lib/sigh/runner.rb:85:in `block in fetch_profiles'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/lib/sigh/runner.rb:82:in `each'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/lib/sigh/runner.rb:82:in `find_all'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/lib/sigh/runner.rb:82:in `fetch_profiles'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/lib/sigh/runner.rb:20:in `run'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/lib/sigh/manager.rb:7:in `start'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/bin/sigh:35:in `block (2 levels) in run'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.36.5/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/bin/sigh:90:in `run'
	from /Users/01006512/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sigh-1.3.1/bin/sigh:108:in `<top (required)>'
	from /Users/01006512/.rbenv/versions/2.2.4/bin/sigh:23:in `load'
	from /Users/01006512/.rbenv/versions/2.2.4/bin/sigh:23:in `<main>'
```

Using [spaceship](https://github.com/fastlane/spaceship/tree/master/lib/spaceship), I can fetch the information of the profile.
```ruby
require 'spaceship'
Spaceship.login
Spaceship.provisioning_profile.in_house.find_by_bundle_id('*')
```

Do you know what's the problem?

**Comment by lacostej** [comment]
This issue is probably related to lack of check in sigh of the `can_download` field before attempting to download all certificates for that profile.
See also http://stackoverflow.com/questions/33747432/unable-to-run-sigh-fastlane/35651678#35651678

Should be fixed here: https://github.com/fastlane/sigh/blob/1.3.1/lib/sigh/runner.rb#L85

by adding something like
```
if !cert.can_download
  UI.info "Skipping cert . Access rights issue ?"
  next
end
```

Spaceship's `download_raw` could probably display something there

https://github.com/fastlane/spaceship/blob/0.21.0/lib/spaceship/portal/certificate.rb#L298

**Comment by uny** [comment]
@lacostej 
i will check it, thank you.

**Comment by uny** [comment]
sure! thank you.
