### ISSUE TITLE
I can't make the sigh download_all for for my Company License for for my Personal License

### ISSUE THREAD

**Issue by sfransen** [fastlane/sigh#274]
Since Cupertino is broken I really Need something to work again.
 Thanks
On a Simple Account this works one a Large  Developer Account it just sits there and never does any thing.
I can't even download one Provision Profile 
 using this command
`Spaceship.provisioning_profile.app_store.find_by_bundle_id("com.xxxxx.xxxxx")` # Hiding AppID

 I works great for my Personal License but. So Have over 1000 Provision profiles and close to 250 AppIDs
 It runs for a every long time and does nothing I abort the command I and I get this.
```
^C-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish': [!] buffer error (Zlib::BufError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `ensure in inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:226:in `body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:163:in `reading_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1412:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/client.rb:277:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/client.rb:195:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/client.rb:276:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/client.rb:252:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/portal_client.rb:329:in `provisioning_profiles'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.22.0/lib/spaceship/portal/provisioning_profile.rb:242:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/download_all.rb:10:in `download_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/lib/sigh/manager.rb:34:in `download_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/bin/sigh:45:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/bin/sigh:91:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.4.0/bin/sigh:109:in `<top (required)>'
	from /usr/bin/sigh:23:in `load'
	from /usr/bin/sigh:23:in `<main>'
```

**Comment by sfransen** [comment]
OK after 25 Minutes of letting it run it did start to load a provisions profiles
[11:00:32]: Successfully logged in
[11:25:45]: Downloading profile 'xxxxxxxxxxxxx'...
 what is it doing for this huge time.
where can I start to look to help on this.

**Comment by sfransen** [comment]
Ok the Problem is the number of Devices we have it our License

 I just tested on another account with lots of Provision Profiles and AppID . But Less UDID in license.
 We have 5000 UDID's is license that is what taking so long for the code to even start.

**Comment by programmin1** [comment]
It takes a long time with many provisioning profiles, even with <30 devices set with AdHoc. I stopped the process after a few minutes. This is an unacceptable amount of time when you can go and find the profiles and download them in seconds using the member center.

**Comment by sfransen** [comment]
Do you have slots of devices in license?
